### ISSUE TITLE
the latest version does not appear to be in the pom.xml file

### ISSUE THREAD

**Issue by dopatraman** [smartystreets/smartystreets-java-sdk#1]
the latest version does not appear to be in the pom.xml file

**Comment by MouaYing** [comment]
@dopatraman - Are you referring to line 9, which says
 `<version>0.0.0</version> <!-- DO NOT EDIT (this is updated by a build job when a new release is published) -->`?

**Comment by mdwhatcott** [comment]
It appears there's nothing to do on this issue. Closing...
