### ISSUE TITLE
Gradle doesn't build on latest version

### ISSUE THREAD

**Issue by Chikrix** [smartystreets/smartystreets-java-sdk#10]
My issue was not being able to import the latest version (3.4.0) into my Android app. I currently use the version `3.3.8` and it doesn't work, but when I upgrade to `3.4.0`, gradle fails to build with error `ERROR: Failed to resolve: com.smartystreets.api:smartystreets-java-sdk:3.4.0`. 

I'm importing this as;
```
implementation 'com.smartystreets.api:smartystreets-java-sdk:3.4.0'
```
That's based on the Maven import structure.

This also doesn't work
```
implementation 'com.github.smartystreets:smartystreets-java-sdk:3.4.0'
```
Which is based on the structure of the old version which works.

**Comment by DuncanBeutler** [comment]
@Chikrix sorry for the delayed response. The latest release documented on github is 3.3.8, I would suggest using that. You said that 3.3.8 isn't working for you though - can you provide more details?
Thanks!

**Comment by DuncanBeutler** [comment]
@Chikrix I'll assume that it's working for you now and close this issue, feel free to reopen this issue if the problem continues!
