### ISSUE TITLE
Docs say to use 3.4.0, latest is 3.3.8

### ISSUE THREAD

**Issue by geoffreyyip** [smartystreets/smartystreets-java-sdk#11]
[The Java SDK Docs](https://smartystreets.com/docs/sdk/java#how-to-get-it) give an example with version `3.4.0`.

The latest artifact I could find was `3.3.8`. https://search.maven.org/artifact/com.smartystreets.api/smartystreets-java-sdk/3.3.8/jar

**Comment by joliver** [comment]
We just released `v3.4.1` to Maven and Github:

https://github.com/smartystreets/smartystreets-java-sdk/releases/tag/3.4.1
https://search.maven.org/search?q=a:smartystreets-java-sdk

Right now Maven says 3.3.8 but it should update within the next few minutes.
