### ISSUE TITLE
buildFilterString separates using "," but API requires ";"

### ISSUE THREAD

**Issue by nihar** [smartystreets/smartystreets-java-sdk#2]
The code in question is in us_autocomplete/Client.java

`
        for (String item : list) {
            filterList += (item + ",");
        }
`

This is invalid according to the [SDK documentation](https://smartystreets.com/docs/cloud/us-autocomplete-api#preference) for building this list, which requires a semi-colon separator.

**Comment by mdwhatcott** [comment]
Right, [preference strings are comma-delimited](https://smartystreets.com/docs/cloud/us-autocomplete-api#preference) but [filter strings are semicolon-delimited](https://smartystreets.com/docs/cloud/us-autocomplete-api#filtering). Good find.

**Comment by nihar** [comment]
Cool. I submitted a pull request but you may have to have two separate methods (one for prefer, one for filter).

**Comment by mdwhatcott** [comment]
Resolved by https://github.com/smartystreets/smartystreets-java-sdk/pull/3
