### ISSUE TITLE
how can we verify a candidate from the client?

### ISSUE THREAD

**Issue by listaction** [smartystreets/smartystreets-java-sdk#20]
hello folks, 
 say we have client side integration that gets the address via client side calls, how can one verify (the candidate) client sends to our service is valid?

1. Does the initial response from smarty contain some type of a hash? 
2. How can one map, Candidate to Lookup if the above is missing (best practice that works for US Street Addresses)?

**Comment by lyledurland** [comment]
I'd love to help you with this question. Can you email your question to support@smartystreets.com?

Thanks!
