### ISSUE TITLE
java.lang.NoClassDefFoundError: java/net/http/HttpClient

### ISSUE THREAD

**Issue by guiramos** [smartystreets/smartystreets-java-sdk#26]
I am having this issue when trying to run some tests.

java.lang.NoClassDefFoundError: java/net/http/HttpClient
	at com.smartystreets.api.GoogleSender.<init>(GoogleSender.java:24)

Isnt java.net.http.HttpClient from Java 11?
That will render your API not compatible with versions prior to 11.

**Comment by SendorWang** [comment]
> I am having this issue when trying to run some tests.
> 
> java.lang.NoClassDefFoundError: java/net/http/HttpClient at com.smartystreets.api.GoogleSender.(GoogleSender.java:24)
> 
> Isnt java.net.http.HttpClient from Java 11? That will render your API not compatible with versions prior to 11.

The same question.

**Comment by DuncanBeutler** [comment]
We made the conscious decision to use Java 11 in the most recent major update of the SDK for its security updates as well as the built in HttpClient. The API itself is still compatible with any version of Java that you are using and previous versions of the SDK will continue to serve your current use cases.
