### ISSUE TITLE
SDK throwing null pointer exception while getting payload from Response

### ISSUE THREAD

**Issue by aniruddh-deserve** [smartystreets/smartystreets-java-sdk#27]
Exception Strace :
java.lang.NullPointerException: Attempt to read from field 'byte[] vz5.payload' on a null object reference
    at com.smartystreets.api.Response.getPayload
    at com.smartystreets.api.us_autocomplete_pro.Client.send(SourceFile:31)

**Comment by DuncanBeutler** [comment]
Can you provide the address that is yielding this error so as to properly reproduce the bug?

**Comment by RyanLCox1** [comment]
I'm going to go ahead and close this as there has been a new release of the sdk. If this is still a problem, please reopen the bug with a full stack trace.
