### ISSUE TITLE
NoClassDefFoundError on latest

### ISSUE THREAD

**Issue by royaldark** [smartystreets/smartystreets-java-sdk#29]
Following the getting started documentation, on latest builds, I get the following error on JDK 8:

```
java.lang.NoClassDefFoundError: java/net/http/HttpClient
	at com.smartystreets.api.GoogleSender.<init>(GoogleSender.java:24)
```

I believe the `java.net.http.HttpClient` is only available in JDK 11+? But documentation says `Java SDK (targets Java 7 or above)` and under requirements `Download and install Java 7 or higher.` Am I missing something?

**Comment by DuncanBeutler** [comment]
If you want to use an earlier version of Java, you'll need to use version 3.11.7 of the SDK or earlier.

**Comment by DuncanBeutler** [comment]
The Changelog has been updated to document this change. Apologies for the breaking change, the corresponding tag should have more effectively reflected that.
