### ISSUE TITLE
Bulk zipcode lookup: Cannot invoke "com.smartystreets.api.Response.getPayload()" because "response" is null

### ISSUE THREAD

**Issue by mstickel-lumatax** [smartystreets/smartystreets-java-sdk#30]
If I construct a batch query to the UsZipCode API using the SS Java SDK as follows:

```
        String authId = System.getenv("ss.authId");
        String authToken = System.getenv("ss.authToken");
        Credentials creds = new StaticCredentials(authId, authToken);
        Client client = new ClientBuilder(creds).buildUsZipCodeApiClient();
        Batch batch = new Batch();
        try {
            batch.add(new Lookup("92093"));
            batch.add(new Lookup("87714"));
            client.send(batch);
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }

```
This results in: 

```
java.lang.NullPointerException: Cannot invoke "com.smartystreets.api.Response.getPayload()" because "response" is null
	at com.smartystreets.api.us_zipcode.Client.send(Client.java:49)

```
Digging into the SDK code, I see that the server is returning HTTP 415.  This is because the SDK by default is not passing a content-type header with the request.

I can work around this by constructing my client with a custom header of "Content-type: application/json" as follows:

```
        Map<String, Object> headers = new HashMap<>();
        headers.put("Content-type", "application/json");
        Client client = new ClientBuilder(creds).withCustomHeaders(headers).buildUsZipCodeApiClient();

```
But shouldn't this header be aded automatically in the SDK client code?  I can't pass any other value for the content type other than "application/json" since JSON what the SDK client sends.

**Comment by DuncanBeutler** [comment]
Content Type header is being set automatically in version 3.12.6 of the SDK.
