### ISSUE TITLE
dependency on google http client still necessary?

### ISSUE THREAD

**Issue by jflebeau** [smartystreets/smartystreets-java-sdk#31]
Hi,

With Java 11 now required (and using the new HttpClient), are the dependencies on google-http-client / http-client-jackson2 really necessary?

**Comment by baohouse** [comment]
Would be helpful to document v3.10.7 as the last release that Java 8 users can use.

**Comment by jflebeau** [comment]
google-http-client was dropped in the last release, but I noticed that apache commons-lang3 was added without related changes...

**Comment by RyanLCox1** [comment]
We've added support back for Java 8 using the OKHttp client. The google-http-client has been dropped.
