### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by marcoRS** [smartystreets/smartystreets-java-sdk#39]
Hello Smartystreets team, 
Thank you for updating your java sdk, my company currently uses it in our Sendwave app and it works great. 

I was wondering, where can one get release notes for the latest update? We tend to attach these notes to PR's when we update our libraries.

**Comment by abbeynels** [comment]
Hi Marco! The Java SDK changelog is located here: https://github.com/smartystreets/changelog/blob/master/sdk/java.md. Please let me know if you have any other questions!
