### ISSUE TITLE
Smarty street is failing to validate valid US addresses

### ISSUE THREAD

**Issue by hammad-tariq** [smartystreets/smartystreets-java-sdk#4]
For example I have tried below Valid US addresses.

Below address is valid but I am getting invalid address in response.
     `
      
      lookup.setStreet("Hartford Street");

      lookup.setCity("San Francisco");

      lookup.setState("CA");

      lookup.setZipCode("94114");`

And 
Wrong City is being returned by the API i.e. Alameda. Also, City is being returned in Country.
          
 `
        
     lookup.setCity("Pleasanton");

     lookup.setStreet("5776 Stoneridge Mall Road");

     lookup.setState("CA");

     lookup.setZipCode("94588");`

I have tried with
`com.smartystreets.api:smartystreets-java-sdk:2.1.2`
and
`com.smartystreets.api:smartystreets-java-sdk:3.2.0`

**Comment by mdwhatcott** [comment]
I suggest you try working with the API demo:

https://smartystreets.com/products/apis/us-street-api

Those addresses appear to be invalid.
