### ISSUE TITLE
ClientBuilder doesn't pass along connection settings to OkHttpClient

### ISSUE THREAD

**Issue by msaavedra-healthgorilla** [smartystreets/smartystreets-java-sdk#46]
I tried doing this:
```
this.client = new ClientBuilder(new StaticCredentials(authId, authToken))
        .withLicenses(license.getLicenses())
        .withMaxTimeout(timeoutSeconds * 1000)
        .buildUsStreetApiClient();
```
and variations of this, but couldn't get it to work. Then I realized that your `ClientBuilder.buildUsStreetApiClient()` calls `SmartySender(int maxTimeout)` constructor.

The `maxTimeout` is ignored and [this constructor](https://github.com/smartystreets/smartystreets-java-sdk/blob/ba9fd95be1121423d902f48cf4156c6aa60aaaec/src/main/java/com/smartystreets/api/SmartySender.java#L28) should be something like this:
```
public SmartySender(int maxTimeout) {
    this.maxTimeOut = maxTimeout;
    this.client = new OkHttpClient.Builder()
                .writeTimeout(this.maxTimeOut, TimeUnit.MILLISECONDS)
                .readTimeout(this.maxTimeOut, TimeUnit.MILLISECONDS)
                .connectTimeout(this.maxTimeOut, TimeUnit.MILLISECONDS)
                .build();
}
```

Are you guys open to PRs from community?

**Comment by RyanLCox1** [comment]
This is fixed now. SmartySender now takes into account the proper maxTimout with this code

SmartySender(int maxTimeOut) {
        this.maxTimeOut = maxTimeOut;
        this.client = new OkHttpClient.Builder()
                .writeTimeout(this.maxTimeOut, TimeUnit.MILLISECONDS)
                .readTimeout(this.maxTimeOut, TimeUnit.MILLISECONDS)
                .connectTimeout(this.maxTimeOut, TimeUnit.MILLISECONDS)
                .build();
    }

I utilized your suggestions from your pull request! Thank you!
