### ISSUE TITLE
Retry wait time after TooManyRequestsResponse hardcoded to 10

### ISSUE THREAD

**Issue by ctucker3** [smartystreets/smartystreets-java-sdk#49]
In the `RetrySender.send` method the client sleeps for 10 seconds when a TooManyRequestsResponse is received. As far as I know SmartyStreets rate limits are based on requests per second, so this wait time seems excessive. It would be ideal if this value was configurable via the `ClientBuilder` like the `maxRetries` used in this class or if it used an incremental backoff like in the `RetrySender.trySend` method. 

The hardcoded wait time section:

```
public Response send(Request request) throws SmartyException, IOException, InterruptedException {
        for(int i = 0; i <= this.maxRetries; ++i) {
            Response response = this.trySend(request, i);
            if (response instanceof TooManyRequestsResponse) {
                long wait = 10L;
...
```

**Comment by RyanLCox1** [comment]
The default is 10 seconds, but you'll notice the lines after the 
long wait = 10L;

 String retryAfter = ((TooManyRequestsResponse) response).getHeaders().get("Retry-After");
                if (retryAfter != null && retryAfter.length() > 0) {
                    wait = Long.parseLong(retryAfter);
                }
                if (wait < 1) {
                    wait = 1L;
                }

Read a header value returned by Smarty servers that tell the client how long to wait.

This value is the actual rate limit wait time. If you retry before that time, you will get another 429.

**Comment by RyanLCox1** [comment]
The `retry-after` header is calculated on the server side. The value it returns is taking into account ALL of the usage of your license from all clients calling the REST API. It's important to obey the value returned so as to not starve any of your processes.
