### ISSUE TITLE
Missing Candidate.inputId property

### ISSUE THREAD

**Issue by peiche** [smartystreets/smartystreets-java-sdk#7]
According to the [output field definitions](https://smartystreets.com/docs/cloud/us-street-api#root), the `input_id` field should be available as identical to the input id defined on the Lookup. However, the [Candidate](https://github.com/smartystreets/smartystreets-java-sdk/blob/master/src/main/java/com/smartystreets/api/us_street/Candidate.java) does not seem to have an inputId property. Please advise.

**Comment by mdwhatcott** [comment]
Because the candidates are all contained on the Lookup object we opted to not duplicate the input_id field on each candidate.

**Comment by peiche** [comment]
Thanks for your quick response.
